![imagen](./img/ejercicios.png)

In [1]:
import numpy as np

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [42]:
my_array = np.arange(10)
rev_array = list(reversed(my_array))
for i,num in enumerate(rev_array):
    if i % 2 != 1:
      print(num,end=" ")
    

9 7 5 3 1 

## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [50]:
my_array = np.arange(10)
print(my_array)
print(my_array[8:6:-1])

[0 1 2 3 4 5 6 7 8 9]
[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [66]:
my_array = np.arange(10)
print(my_array[2::-1])

[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [69]:
matriz = np.arange(1, 21).reshape(4, 5)
print(matriz)
print()
matriz_invertida = matriz[::-1, ::-1]
print(matriz_invertida)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


In [74]:
"""_summary_
import numpy as np
matriz = np.arange(1, 21).reshape(4, 5)
print(matriz)
matriz_invertida = np.fliprl(np.flipud(matriz))
print(matriz_invertida)  
"""

'_summary_\nimport numpy as np\nmatriz = np.arange(1, 21).reshape(4, 5)\nprint(matriz)\nmatriz_invertida = np.fliprl(np.flipud(matriz))\nprint(matriz_invertida)  \n'

## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [84]:
matriz = np.arange(1, 21).reshape(4, 5)
print(matriz)
print()
submatriz = matriz[:2, :2] #filas/columnas
print(submatriz)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

[[1 2]
 [6 7]]


## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [95]:
matriz = np.arange(1, 21).reshape(4, 5)
print(matriz)
print()
submatriz = np.array([matriz[0,0::2],matriz[2,0::2]])
print(submatriz)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

[[ 1  3  5]
 [11 13 15]]


## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [99]:
import numpy as np

matriz = np.arange(1, 21).reshape(4, 5)
matriz_invertida = np.flip(matriz, axis=1) #para filas
matriz_final = matriz_invertida[:-1]
print(matriz_final)

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [100]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
print(x[np.where(x == "Loro")])

['Loro' 'Loro']


In [101]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
mascara = x == "Loro"
loros = x[mascara]
print(loros)

['Loro' 'Loro']


## Ejercicio 9
Crea una secuencia de 20 elementos y transfórmala en un array compuesto por 2 matrices de 5x2

In [105]:
secuencia = np.arange(20)
print(secuencia.reshape(2,5,2))

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]


## Ejercicio 10

Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [117]:
array = np.zeros(10)
print(array)
print(array.nbytes)
array[3]=1
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
80
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


## Ejercicio 11

Crea un vector que vaya del 10 al 49

Inviértelo

In [120]:
vector = np.arange(10,50)
print(vector)
print()
print(vector[49::-1])


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejercicio 12
Encuentra los índices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/) Encapsúlalo en una función, con un argumento de entrada de un vector.

In [122]:
def indices_no_cero(vector):
    return np.nonzero(vector)[0]

vector = np.array([1, 2, 0, 0, 4, 0])
resultado = indices_no_cero(vector)
print(resultado)

[0 1 4]


## Ejercicio 13
Crea una matriz de números aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [129]:
import random
matriz = np.random.randint(0,101,size=(10,10)) 
print(matriz)
minimo = np.min(matriz)
maximo = np.max(matriz)
print("El mínimo es: ", minimo)
print("El máximo es: ", maximo)

[[ 18   4  75  82  31  10  85  88  44  44]
 [ 31   0  32  72  53  91  68  78  13  46]
 [ 41  76  62  35  62  95  44 100  29  41]
 [ 35  81  47   9   0  33  81  12  77  32]
 [ 67   9  25  48   2  78  71  14  85  46]
 [ 51  54  85  87  86  72  62  32   0  68]
 [ 70  64   4  44  51  83  51   1  18  27]
 [ 18  99   3  76  82  42  89  36  49  50]
 [ 59  51  83  60  12  89  81  94  12  47]
 [  9  14  93  54  48   4  54  37  20 100]]
El mínimo es:  0
El máximo es:  100


## Ejercicio 14
Crea un vector aleatorio de tamaño 30 y calcula su media

In [136]:
vector_aleatorio = np.random.randint(0,101,size=30)
print(vector_aleatorio)
print("La media es:",np.mean(vector_aleatorio))

[100  75  43  91  95  95  50   2  85  93   0  32  67  71  54  89  46  30
  73  28  69  28  53  38   1  64  88  86  85  55]
La media es: 59.53333333333333


## Ejercicio 15
Crea un array cuadrado de 2D, con las dimensiones que quieras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [139]:
def crear_matriz(dimension):
    matriz = np.ones((dimension, dimension), dtype=int)
    # Rellenar de unos su interior de la siguiente forma:
    if dimension > 2:
        matriz[1:-1, 1:-1] = 0
    return matriz

dimension = int(input("Introduce la dimensión que quieras emplear: "))
resultado = crear_matriz(dimension)
print(resultado)

[[1 1 1 1 1 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 1 1 1 1 1]]


## Ejercicio 16
Crea una matriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [143]:
matriz = np.zeros((8, 8), dtype=int)
matriz[:, 1::2] = 1
matriz[1::2, :] = 1 - matriz[1::2, :] 
print(matriz)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 17
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [146]:
mat = np.array([0, 1])
fila = np.tile(mat, 4)
matriz = np.tile(fila,(8, 1))  
matriz[1::2] = 1 - matriz[1::2]
print(matriz)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 18
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [147]:
matriz = np.random.rand(5, 5)
media = np.mean(matriz)
desviacion_estandar = np.std(matriz)
# Normalizamos la matriz
matriz_normalizada = (matriz - media) / desviacion_estandar


print(matriz)
print()
print(matriz_normalizada)

[[0.45931646 0.05158532 0.54091914 0.66901208 0.86853598]
 [0.8942999  0.66957428 0.94901763 0.54413076 0.67052981]
 [0.70256567 0.59365902 0.99526851 0.40548536 0.76592136]
 [0.31600074 0.04008611 0.18220888 0.87290769 0.82987715]
 [0.15395473 0.36720931 0.74491325 0.61875538 0.6776206 ]]

[[-0.45912954 -1.96860237 -0.15702597  0.31719044  1.05585343]
 [ 1.15123476  0.31927178  1.35380682 -0.14513616  0.32280927]
 [ 0.44141014  0.03822378  1.52503349 -0.65841918  0.67596101]
 [-0.98970269 -2.01117393 -1.48501725  1.07203807  0.91273351]
 [-1.58961771 -0.800122    0.5981863   0.13113373  0.34906029]]


## Ejercicio 19
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [150]:
secuencia = list(range(11))
print(secuencia)

array = [-1 if 3 <= x <= 8 else x for x in secuencia]
print(array)

array = [-x if 3 <= x <= 8 else x for x in secuencia]
print(array)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[0, 1, 2, -1, -1, -1, -1, -1, -1, 9, 10]
[0, 1, 2, -3, -4, -5, -6, -7, -8, 9, 10]
