![imagen](./img/ejercicios.png)

## Ejercicio 1
Importa el módulo de `numpy` y obtén su versión.

In [1]:
import numpy as np

In [2]:
np.__version__

'2.0.2'

## Ejercicio 2
Crea un array de una dimensión que vaya de 0 a 9. Llamalo `my_array`

In [3]:
my_array = np.arange(10)
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


## Ejercicio 3
Crea un array 3x3, que sea todo a True

In [15]:
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
booli = np.where(array>0,True,False)
print(booli)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


## Ejercicio 4
Extrae todos los impares de `my_array`

In [29]:
print((my_array[1:10:2]))

[1 3 5 7 9]


In [ ]:
# and = &
# or = |
# not = ~

## Ejercicio 5
En un nuevo array, sustituye todos los impares de `my_array` por -1

In [37]:
my_array = np.arange(10)
my_array[my_array%2!=0] = -1
print(my_array)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


## Ejercicio 6
En un nuevo array, sustituye todos los impares de `my_array` por -1. Esta vez usa `where`

In [33]:
my_array_nuevo = np.where(my_array %2 == 0,my_array,-1)
print(my_array_nuevo)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


## Ejercicio 7
Convierte `my_array` en un nuevo array de dos dimensiones mediante `reshape`.

In [43]:
my_array = np.arange(10).reshape((2,5))
print(my_array)

[[0 1 2 3 4]
 [5 6 7 8 9]]


## Ejercicio 8
Concatena los siguientes arrays verticalmente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [44]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
resultado = np.vstack((a, b))
print(resultado)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [ ]:
#vstack --> Para concatenarlo de manera vertical
#hstack --> Para concatenarlo de manera horizontal

In [47]:
array_concatenado = np.concatenate((a,b),axis=0)
print(array_concatenado)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


## Ejercicio 9
Concatena los siguientes arrays horizontamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [45]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
resultado = np.hstack((a, b))
print(resultado)

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [46]:
array_concatenado = np.concatenate((a,b),axis=1)
print(array_concatenado)

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


## Ejercicio 10
Encuentra todos los elementos en común entre ambos arrays. [Para ello usa la función `intersect1d`](https://numpy.org/doc/stable/reference/generated/numpy.intersect1d.html)

```Python
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

In [48]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
result = np.intersect1d(a,b)
print(result)

[2 4]


## Ejercicio 11
Obtén la documentación acerca de la función `concatenate`

In [49]:
help(np.concatenate)

Help on _ArrayFunctionDispatcher in module numpy:

concatenate(...)
    concatenate(
        (a1, a2, ...), 
        axis=0, 
        out=None, 
        dtype=None, 
        casting="same_kind"
    )
    
    Join a sequence of arrays along an existing axis.
    
    Parameters
    ----------
    a1, a2, ... : sequence of array_like
        The arrays must have the same shape, except in the dimension
        corresponding to `axis` (the first, by default).
    axis : int, optional
        The axis along which the arrays will be joined.  If axis is None,
        arrays are flattened before use.  Default is 0.
    out : ndarray, optional
        If provided, the destination to place the result. The shape must be
        correct, matching that of what concatenate would have returned if no
        out argument were specified.
    dtype : str or dtype
        If provided, the destination array will have this dtype. Cannot be
        provided together with `out`.
    
        .. versionadded

## Ejercicio 12
Crea un array unidimensional que vaya del 0 al 9. Llámalo `my_array`. 
1. Multiplica cada uno de los elementos de `my_array` por 10, en un nuevo array
2. Accede al primer elemento de `my_array`
3. Accede al último elemento de `my_array`
4. Imprime por pantalla los numeros del 1 al 7 de `my_array`

In [50]:
my_array = np.arange(10)
print(my_array)


[0 1 2 3 4 5 6 7 8 9]


In [52]:
my_array *= 10
print(my_array)

[ 0 10 20 30 40 50 60 70 80 90]


In [53]:
print(my_array[0])

0


In [54]:
print(my_array[-1])

90


In [55]:
print(my_array[1:8])

[10 20 30 40 50 60 70]


## Ejercicio 13
Crea un array manualmente de tres filas por tres columnas. Llámalo `my_matrix`

In [60]:
my_matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(my_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [59]:
my_matrix = np.arange(1,10).reshape(3,3)
print(my_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Ejercicio 14
Obtén la siguiente secuencia:

```Python
[ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49]
```

In [64]:
secuencia = np.arange(1,50,3)
print(secuencia)

[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49]


## Ejercicio 15
Obtén la siguiente secuencia

```Python
[4., 3.75, 3.5 , 3.25, 3.  , 2.75, 2.5 , 2.25, 2., 1.75, 1.5 ,1.25]
```

In [67]:
secuencia = np.arange(4,1,-0.25)
print(secuencia)

[4.   3.75 3.5  3.25 3.   2.75 2.5  2.25 2.   1.75 1.5  1.25]


## Ejercicio 16
Lee la imagen "numpy.png"

In [71]:
imagen = np.array('./img/numpy.png')
print(type(imagen))
print(imagen.shape)

<class 'numpy.ndarray'>
()


## Ejercicio 17
Crea un array de 4x1. A continuación convierte el array a un 2x2

In [74]:
array4x1 = np.array([[1], [2], [3], [4]])
print("Array (4x1):")
print(array4x1)
array2x2 = array4x1.reshape(2, 2)
print("Array (2x2):")
print(array2x2)

Array (4x1):
[[1]
 [2]
 [3]
 [4]]
Array (2x2):
[[1 2]
 [3 4]]


## Ejercicio 18
Crea una secuencia aleatoria. La secuencia se tiene que componer de 4 matrices de 5x3. Serían 3 dimensiones diferentes.

In [77]:
print(np.random.randint(5,size=(5,3)))
print(np.random.randint(5,size=(5,3)))
print(np.random.randint(5,size=(5,3)))
print(np.random.randint(5,size=(5,3)))
print(np.random.randint(5,size=(5,3)))

[[4 2 4]
 [4 3 3]
 [1 1 4]
 [4 4 4]
 [3 0 3]]
[[0 2 4]
 [4 3 0]
 [1 3 2]
 [0 1 1]
 [2 0 4]]
[[4 3 2]
 [0 1 0]
 [1 2 2]
 [0 0 3]
 [2 2 3]]
[[3 3 2]
 [4 2 2]
 [4 3 4]
 [3 3 3]
 [3 3 2]]
[[2 0 1]
 [1 3 3]
 [4 0 2]
 [3 0 1]
 [1 0 4]]


In [78]:
print(np.random.rand(4,5,3))

[[[5.40915827e-01 2.28527387e-01 2.99300588e-01]
  [6.91968944e-01 4.22881096e-01 8.17528672e-01]
  [7.71290832e-01 7.36354936e-01 3.81184123e-01]
  [8.78286569e-01 4.93989600e-01 2.16852322e-02]
  [5.35005879e-01 2.63040847e-02 6.64928203e-01]]

 [[4.90566496e-01 6.76589400e-01 7.90932815e-02]
  [8.95959394e-01 4.53914272e-01 7.58946030e-01]
  [8.80150697e-01 1.81761796e-04 1.39036411e-01]
  [9.14541090e-01 7.38820713e-01 3.45456129e-01]
  [8.84803857e-01 9.92882763e-01 4.42138647e-01]]

 [[4.51822047e-01 7.04324994e-01 2.40382131e-01]
  [5.19521326e-01 2.33286916e-01 8.38427422e-01]
  [2.73835234e-01 3.42419912e-01 8.71691959e-01]
  [8.21179708e-01 2.75507692e-01 2.31610650e-01]
  [8.97765722e-02 4.68530723e-01 2.74524665e-01]]

 [[3.87693473e-01 1.13554129e-02 4.92642381e-01]
  [6.92019243e-01 2.43534999e-01 6.24987714e-01]
  [6.24668661e-01 4.96495536e-01 2.16597828e-02]
  [9.22461714e-01 7.15493391e-01 9.28308765e-01]
  [3.71219707e-01 6.40438547e-01 5.81657543e-01]]]


## Ejercicio 19
Crea una matriz de 10x1, toda ella compuesta por `False`. Después transformalo en un 2x5

In [80]:

matriz = np.zeros((10, 1), dtype=bool)
print("Matriz de (10x1):")
print(matriz)
nueva_matriz = matriz.reshape(2, 5)
print("\nNueva matriz de (2x5):")
print(nueva_matriz)

Matriz de (10x1):
[[False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]]

Nueva matriz de (2x5):
[[False False False False False]
 [False False False False False]]


## Ejercicio 20
Dado el siguiente array

```Python
x = np.random.randint(10, 20, size = (5,2,6))
```

1. ¿Cuántos elementos tiene el array?
2. ¿Cuántas dimensiones?
3. ¿Cuánta es la longitud cada dimensión?

In [7]:
#Para saber cuantos elementos tiene hacemos: size=(5,2,6) --> 5*2*6 = 60 elementos
#Tiene 3 dimensiones
#La longitud de cada dimensión es de 20

[[[18 13 10 14 16 11]
  [18 19 17 15 12 18]]

 [[14 10 14 14 18 11]
  [10 12 13 15 15 16]]

 [[12 16 17 11 19 14]
  [11 14 11 18 10 14]]

 [[10 10 19 19 12 14]
  [12 18 11 19 13 17]]

 [[17 15 18 12 14 13]
  [10 13 17 12 13 10]]]
