![imagen](./img/ejercicios.png)

In [2]:
import numpy as np

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [3]:
my_array = np.arange(10)
rev_array = list(reversed(my_array))
for i,num in enumerate(rev_array):
    if i % 2 != 1:
      print(num,end=" ")
    

9 7 5 3 1 

In [4]:
my_array = np.arange(10)
print(my_array[::-2])

[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [5]:
my_array = np.arange(10)
print(my_array)
print(my_array[8:6:-1])

[0 1 2 3 4 5 6 7 8 9]
[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [6]:
my_array = np.arange(10)
print(my_array[2::-1])

[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [69]:
matriz = np.arange(1, 21).reshape(4, 5)
print(matriz)
print()
matriz_invertida = matriz[::-1, ::-1]
print(matriz_invertida)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


In [8]:
import numpy as np
matriz = np.arange(1, 21).reshape(4, 5)
print(matriz)
print()
matriz_invertida = np.fliplr(np.flipud(matriz))
print(matriz_invertida)  

#flip --> función para dar la vuelta

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [9]:
matriz = np.arange(1, 21).reshape(4, 5)
print(matriz)
print()
submatriz = matriz[:2, :2] #filas/columnas
print(submatriz)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

[[1 2]
 [6 7]]


## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [12]:
matriz = np.arange(1, 21).reshape(4, 5)
print(matriz)
print()
submatriz = np.array([matriz[0,0::2],matriz[2,0::2]])
print(submatriz)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

[[ 1  3  5]
 [11 13 15]]


In [11]:
sub_array_2 = matriz[0:5:2,:6:2]
print(sub_array_2)

[[ 1  3  5]
 [11 13 15]]


## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [13]:
import numpy as np

matriz = np.arange(1, 21).reshape(4, 5)
matriz_invertida = np.flip(matriz, axis=1) #para filas
matriz_final = matriz_invertida[:-1]
print(matriz_final)

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [14]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
print(x[np.where(x == "Loro")])

['Loro' 'Loro']


In [15]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
mascara = x == "Loro"
loros = x[mascara]
print(loros)

['Loro' 'Loro']


## Ejercicio 9
Crea una secuencia de 20 elementos y transfórmala en un array compuesto por 2 matrices de 5x2

In [16]:
secuencia = np.arange(20)
print(secuencia.reshape(2,5,2))

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]


## Ejercicio 10

Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [18]:
array = np.zeros(10)
print(array)
print(array.nbytes)
array[3]=1
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
80
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


## Ejercicio 11

Crea un vector que vaya del 10 al 49

Inviértelo

In [19]:
vector = np.arange(10,50)
print(vector)
print()
print(vector[49::-1])


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejercicio 12
Encuentra los índices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/) Encapsúlalo en una función, con un argumento de entrada de un vector.

In [20]:
def indices_no_cero(vector):
    return np.nonzero(vector)[0]

vector = np.array([1, 2, 0, 0, 4, 0])
resultado = indices_no_cero(vector)
print(resultado)

[0 1 4]


## Ejercicio 13
Crea una matriz de números aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [26]:
import random
matriz = np.random.randint(0,101,size=(10,10)) 
print(matriz)
minimo = np.min(matriz)
maximo = np.max(matriz)
print()
print("El mínimo es: ", minimo)
print("El máximo es: ", maximo)

[[ 14  67  42  97   9  79  68  51  30  46]
 [ 80  73  23  96  12  33  90  96  70  80]
 [ 91  94  83  75  72  77  73  15  70  35]
 [ 57  95  22  37  18  86  44  38  92  50]
 [ 87  25  39  49  25  64  34   4  91  80]
 [ 12  14  98   5  86  48  60  81   7  52]
 [ 43  57  53  95  42  28  59  11  80  26]
 [ 22  92  51  65  22   9 100  70  89  26]
 [ 92  91  82   7  96  19  25   8  87  35]
 [ 35  84  77  94  34  52  38  98  79  13]]

El mínimo es:  4
El máximo es:  100


## Ejercicio 14
Crea un vector aleatorio de tamaño 30 y calcula su media

In [27]:
vector_aleatorio = np.random.randint(0,101,size=30)
print(vector_aleatorio)
print()
print("La media es:",np.mean(vector_aleatorio))

[38  0 27 61 13 34 28 81 94 41 65  4  7 71 22 30 77 59 48 68 87 80 20 17
 54 36 45 39 15 48]

La media es: 43.63333333333333


## Ejercicio 15
Crea un array cuadrado de 2D, con las dimensiones que quieras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [31]:
def crear_matriz(dimension):
    matriz = np.ones((dimension, dimension), dtype=int)
    # Rellenar de unos su interior de la siguiente forma:
    if dimension > 2:
        matriz[1:-1, 1:-1] = 0
    return matriz

dimension = int(input("Introduce la dimensión que quieras emplear: "))
resultado = crear_matriz(dimension)
print(resultado)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


## Ejercicio 16
Crea una matriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [34]:
matriz = np.zeros((8, 8), dtype=int)
matriz[:, 1::2] = 1
matriz[1::2, :] = 1 - matriz[1::2, :] 
print(matriz)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 17
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [33]:
mat = np.array([0, 1])
fila = np.tile(mat, 4)
matriz = np.tile(fila,(8, 1))  
matriz[1::2] = 1 - matriz[1::2]
print(matriz)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 18
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [35]:
matriz = np.random.rand(5, 5)
media = np.mean(matriz)
desviacion_estandar = np.std(matriz)
# Normalizamos la matriz
matriz_normalizada = (matriz - media) / desviacion_estandar


print(matriz)
print()
print(matriz_normalizada)

[[0.54924595 0.78170568 0.23068806 0.11697752 0.97573272]
 [0.56634294 0.45822048 0.40308174 0.47884928 0.97260798]
 [0.92065037 0.93855373 0.21093037 0.92988768 0.92037746]
 [0.09748646 0.8932631  0.96366817 0.86959123 0.08962951]
 [0.85525618 0.65550537 0.67223178 0.49875619 0.97910452]]

[[-0.30103167  0.46052448 -1.34465206 -1.71717661  1.09617211]
 [-0.24502061 -0.59923819 -0.77987697 -0.53165662  1.08593521]
 [ 0.91571806  0.97437087 -1.40937976  0.94598022  0.91482399]
 [-1.78103083  0.82599523  1.05664771  0.74844436 -1.8067708 ]
 [ 0.7014816   0.04708244  0.10187946 -0.46644003  1.10721839]]


## Ejercicio 19
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [39]:
secuencia = list(range(11))
print(secuencia)

array = [-1 if 3 <= x <= 8 else x for x in secuencia]
print(array)

array = [-x if 3 <= x <= 8 else x for x in secuencia]
print(array)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[0, 1, 2, -1, -1, -1, -1, -1, -1, 9, 10]
[0, 1, 2, -3, -4, -5, -6, -7, -8, 9, 10]
